### ISSUE TITLE
Stackable - support injecting a custom z-index to an ancestor of multiple Stackables

### ISSUE THREAD

**Issue by yairEO** [open-amdocs/webrix#105]
### Allow changing the initial `z-index` for a all `<Stackable>` components within a common ancestor.

In the below image, all the "pink" boxed should appear above the white boxes:

[![image](https://user-images.githubusercontent.com/845031/200190898-2768fa3c-734c-48ef-8c94-c05ec38f9b31.png)](https://codesandbox.io/s/webrix-stackables-context-opqyek?file=/Example.jsx)

### Proposed solution:

By exposing the `context` it would allow doing this: (`Stackable.Provider` points to the [context](https://github.com/open-amdocs/webrix/blob/master/src/components/Stackable/Stackable.context.js) provider)

```jsx
export default () => (
    <>
        <div class='higher'>
			<Stackable.Provider value={{zIndex: 50}}>
	            <Stackable className='stacking special'/>
	            <Stackable className='stacking special'/>
				<div class='deep_deep_child_somewhere'>
					<Stackable className='stacking special'/>
                </div>
			</Stackable.Provider>
        </div>

        <Stackable className='stacking '>
            <Stackable className='stacking'>
                <Stackable className='stacking'/>
            </Stackable>
        </Stackable>
    </>
);
```

A use-case would be a site's header with popups or dropdowns which are implemented with `Stackable` and their `z-index` should start from a minimum value which is above the rest of the website's main content area.

Clearly custom `z-index` value can be given as a `prop` for every `Stackable` component within the common `.higher` ancestor, but is not a "clean" solution as lift the whole initial `z-index` entirely, as a "group".

**Comment by ykadosh** [comment]
I think this is already possible using the `zIndex` prop. Here's a [sandbox](https://codesandbox.io/s/elated-drake-3hxyev?file=/Example.jsx).

```jsx
<div>
    <Stackable className="stacking special" zIndex={20} />
</div>
<div>
    <Stackable className="stacking">
        <Stackable className="stacking">
            <Stackable className="stacking" />
        </Stackable>
    </Stackable>
</div>
```

**Comment by yairEO** [comment]
Yes it is possible for a single `Stackable` but not to a group of unknown number of them which are coded within a specific area in a webpage, for a example, a *header* section with many tooltips and popups which should all appear above any other `Stackable` that originates within the content area, below the header section.

It is possible to manually modify each of these `Stackable` (which are not nested within each-other) and have the same result mentioned above, a developer (in a team) might not be aware this should be done for every new `Stackable` component written within a certain area of the webpage/app

**Comment by ykadosh** [comment]
I see, in that case context makes sense.
