### ISSUE TITLE
Movable - update callback is fired unnecessarily when has snap

### ISSUE THREAD

**Issue by yairEO** [open-amdocs/webrix#35]
## Steps to reproduce:
1. got to: https://codesandbox.io/s/quizzical-greider-szyr3?file=/Example.jsx
2. grab (with the mouse) the movable element and move the mouse just a little bit so the element doesn't move
3. see the `update` callback is fired many times, even through the component hasn't moved.

https://user-images.githubusercontent.com/845031/117292532-fedae900-ae78-11eb-8cf1-c7e4e372706c.mp4

It's worth internally wrapping the callback with [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) if not already done

**Comment by ykadosh** [comment]
Thanks Yair, that's a good point. I think we can solve this by maintaining the previous coordinates through `shared`, and only calling `update` when the coordinates change.
