### ISSUE TITLE
Movable - when "contain" is defined with "snap", movable element should use snapping relative to container

### ISSUE THREAD

**Issue by yairEO** [open-amdocs/webrix#36]
https://codesandbox.io/s/quizzical-greider-szyr3?file=/Example.jsx

In the above example the expected behavior is the movable element will snap by `50` jumps inside the container, which has `250 x 250` size, regardless of where it is positioned on the screen

**Comment by ykadosh** [comment]
That's a good point, but i'm not sure how we can achieve this, since operations are standalone and should not depend on each other. Perhaps the `relative(ref)` operation discussed in #37 can solve this.

**Comment by ykadosh** [comment]
This will be tracked in #37 , closing for now
