### ISSUE TITLE
Position values returned from `update` method are not exact

### ISSUE THREAD

**Issue by yairEO** [open-amdocs/webrix#41]
https://codesandbox.io/s/agitated-wind-5j6t9?file=/Example.jsx

https://user-images.githubusercontent.com/845031/118973858-d07e0300-b97a-11eb-9037-da299a5f4c28.mp4

### Steps to reproduce:
When simply clicking the movable element (not dragging) -  callback is fired with undesired / values. 

### Expected:
values should be an **exact** multiply of the  setting value (which is set to in this example ) 

### What is happening instead?
Need to investigate **why** this is happening and not simply *round* before sending the position values

    {left: 199.9999771118164, top: 99.98579406738281}
    
This might seem insignificant, but is has huge impact on some use-cases

_Originally posted by @yairEO in https://github.com/open-amdocs/webrix/issues/37#issuecomment-845028767_

**Comment by ykadosh** [comment]
I was able to reproduce this when zooming in/out.
