### ISSUE TITLE
[BUG] Collapse nested Collapsible at the same time, the height is wrong

### ISSUE THREAD

**Issue by xialvjun** [open-amdocs/webrix#57]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page

https://codesandbox.io/s/friendly-glitter-vt6vg?file=/Example.jsx

### Explanation

- **What is the expected behavior?**
I use just one state to control all the four Collapsible elements, when I change the state, I hope it works right.

- **What is happening instead?**
Wrong parent height.

- **What error message are you getting?**

**Comment by ykadosh** [comment]
Hi @xialvjun, thanks for reporting. This is indeed a bug.
@yairEO care to take a look?

**Comment by yairEO** [comment]
I will look, thanks for reporting!
