### ISSUE TITLE
New UI component

### ISSUE THREAD

**Issue by prajwalkulkarni** [open-amdocs/webrix#74]
This component idea is specific to NextJs and not React in general. The component is about creating and managing portals(mostly used as portals). The absence of `index.js` in NextJS projects, makes it difficult to create a portal and, even if one manages to create one, animating portals on mounting and unmounting is an overhead. To tap into both these issues and give a single-stop solution, I've created [NextPortal](https://www.npmjs.com/package/nextportal). I wanted to contribute to this repository and in the "contributing" tab it was instructed that I open an issue for the proposed component. NextPortal is my first open-source project and, I was wondering if my project could be a part of this organization/collection.

Looking forward to hearing back from you.
Regards,
Prajwal

**Comment by ykadosh** [comment]
Hi @prajwalkulkarni, I think you would want to open this PR in the Next.js repo, not here :)
